# Название нашего CI-пайплайна, которое будет отображаться в GitHub
name: Python CI

# Указываем, когда запускать этот пайплайн
on:
  # Запускать при каждом push в ветку main
  push:
    branches: [ main ]
  # Запускать при создании Pull Request в ветку main
  pull_request:
    branches: [ main ]

# Определяем задачи (jobs), которые нужно выполнить
jobs:
  build:
    # Указываем, на какой операционной системе запускать (Ubuntu - стандарт для CI)
    runs-on: ubuntu-latest

    # Шаги (steps), которые нужно выполнить последовательно
    steps:
    # Шаг 1: Скачиваем код из нашего репозитория
    - name: Checkout repository
      uses: actions/checkout@v4

    # Шаг 2: Настраиваем Python нужной нам версии
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # Шаг 3: Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest

    # Шаг 4: Проверяем стиль кода с помощью flake8
    - name: Lint with flake8
      run: |
        # --count покажет общее число ошибок
        # --exit-zero никогда не завершит сборку с ошибкой, только покажет предупреждения
        # --max-complexity=10, --max-line-length=127, --statistics - полезные флаги для статистики
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Шаг 5: Запускаем тесты с помощью pytest
    - name: Test with pytest
      run: |
        pytest